"""Windows 任务计划中的 daemon 安装与控制。"""

from __future__ import annotations

import csv
import json
import locale
import os
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from xml.etree import ElementTree as ET

from xianyu_agent.config import get_settings

TASK_NAME = "XianyuAgent-Daemon"
WATCHDOG_TASK_NAME = "XianyuAgent-Watchdog"
TASK_NAMESPACE = "http://schemas.microsoft.com/windows/2004/02/mit/task"
SYSTEM_SID = "S-1-5-18"
TASK_RESULT_LABELS = {
    0: "success",
    0x00041300: "ready",
    0x00041301: "running",
    0x00041302: "disabled",
    0x00041303: "not_run",
    0x00041304: "no_more_runs",
    0x00041305: "not_scheduled",
    0x00041306: "terminated",
    0x00041307: "no_valid_triggers",
    0x00041308: "event_trigger",
    0x800710E0: "request_refused",
}


class WindowsServiceError(RuntimeError):
    """任务计划命令失败。"""


@dataclass(frozen=True)
class TaskPaths:
    project_root: Path
    python_executable: Path
    pythonw_executable: Path
    xml_path: Path
    watchdog_xml_path: Path


@dataclass(frozen=True)
class ScheduledTaskStatus:
    installed: bool
    state: str = "not_installed"
    last_run_time: str | None = None
    last_task_result: int | None = None
    next_run_time: str | None = None


def format_task_result(value: int | None) -> str:
    if value is None:
        return "-"
    label = TASK_RESULT_LABELS.get(value, "unknown")
    return f"{label} (0x{value:08X})"


def resolve_task_paths(*, project_root: Path | None = None) -> TaskPaths:
    root = (project_root or Path(__file__).resolve().parents[3]).resolve()
    python_executable = Path(sys.executable).resolve()
    pythonw_executable = python_executable.with_name("pythonw.exe")
    if os.name == "nt" and not pythonw_executable.exists():
        msg = f"pythonw.exe 不存在:{pythonw_executable}"
        raise WindowsServiceError(msg)
    xml_path = root / "data" / "runtime" / "scheduled-task.xml"
    watchdog_xml_path = root / "data" / "runtime" / "watchdog-task.xml"
    return TaskPaths(
        project_root=root,
        python_executable=python_executable,
        pythonw_executable=pythonw_executable,
        xml_path=xml_path,
        watchdog_xml_path=watchdog_xml_path,
    )


def current_user_sid() -> str:
    _require_windows()
    result = _run(["whoami.exe", "/user", "/fo", "csv", "/nh"])
    rows = list(csv.reader(result.stdout.splitlines()))
    if not rows or len(rows[0]) < 2:
        msg = "无法从 whoami 读取当前用户 SID"
        raise WindowsServiceError(msg)
    return rows[0][-1].strip()


def build_task_xml(
    paths: TaskPaths,
    *,
    startup: str,
    user_sid: str | None = None,
) -> str:
    """生成任务 XML;不含 Cookie、Token 或环境变量值。"""
    if startup not in {"user", "system"}:
        msg = f"unsupported startup mode: {startup}"
        raise ValueError(msg)
    if startup == "user" and not user_sid:
        msg = "user startup requires user_sid"
        raise ValueError(msg)
    ET.register_namespace("", TASK_NAMESPACE)
    root = ET.Element(_tag("Task"), {"version": "1.4"})
    _add_registration(root)
    principal_sid, logon_type, run_level = _add_trigger(
        root, startup=startup, user_sid=user_sid
    )
    _add_principal(
        root,
        principal_sid=principal_sid,
        logon_type=logon_type,
        run_level=run_level,
    )
    _add_settings(root)
    _add_action(root, paths)
    return ET.tostring(root, encoding="unicode", xml_declaration=False)


def build_watchdog_task_xml(
    paths: TaskPaths,
    *,
    startup: str,
    user_sid: str | None = None,
) -> str:
    """生成每分钟运行一次的 watchdog 任务 XML。"""
    if startup not in {"user", "system"}:
        msg = f"unsupported startup mode: {startup}"
        raise ValueError(msg)
    if startup == "user" and not user_sid:
        msg = "user startup requires user_sid"
        raise ValueError(msg)
    ET.register_namespace("", TASK_NAMESPACE)
    root = ET.Element(_tag("Task"), {"version": "1.4"})
    _add_registration(root, description="xianyu-agent daemon watchdog")
    principal_sid, logon_type, run_level = _add_trigger(
        root,
        startup=startup,
        user_sid=user_sid,
    )
    _add_periodic_trigger(root)
    _add_principal(
        root,
        principal_sid=principal_sid,
        logon_type=logon_type,
        run_level=run_level,
    )
    _add_settings(root, execution_limit="PT1M", restart_on_failure=False)
    _add_action(root, paths, module="xianyu_agent.services.watchdog_runner")
    return ET.tostring(root, encoding="unicode", xml_declaration=False)


def _add_registration(
    root: ET.Element,
    *,
    description: str = "xianyu-agent WebSocket daemon; generated by xianyu-agent service install",
) -> None:
    registration = ET.SubElement(root, _tag("RegistrationInfo"))
    ET.SubElement(registration, _tag("Author")).text = "xianyu-agent"
    ET.SubElement(registration, _tag("Description")).text = description


def _add_trigger(
    root: ET.Element,
    *,
    startup: str,
    user_sid: str | None,
) -> tuple[str, str, str]:
    triggers = ET.SubElement(root, _tag("Triggers"))
    if startup == "system":
        trigger = ET.SubElement(triggers, _tag("BootTrigger"))
        ET.SubElement(trigger, _tag("Enabled")).text = "true"
        ET.SubElement(trigger, _tag("Delay")).text = "PT30S"
        principal_sid = SYSTEM_SID
        logon_type = "ServiceAccount"
        run_level = "HighestAvailable"
    else:
        trigger = ET.SubElement(triggers, _tag("LogonTrigger"))
        ET.SubElement(trigger, _tag("Enabled")).text = "true"
        ET.SubElement(trigger, _tag("UserId")).text = user_sid
        principal_sid = str(user_sid)
        logon_type = "InteractiveToken"
        run_level = "LeastPrivilege"
    return principal_sid, logon_type, run_level


def _add_periodic_trigger(root: ET.Element) -> None:
    """增加从安装时刻开始的每分钟触发,无需等待下一次登录或重启。"""
    triggers = root.find(_tag("Triggers"))
    if triggers is None:
        msg = "task XML has no Triggers element"
        raise ValueError(msg)
    trigger = ET.SubElement(triggers, _tag("TimeTrigger"))
    repetition = ET.SubElement(trigger, _tag("Repetition"))
    ET.SubElement(repetition, _tag("Interval")).text = "PT1M"
    ET.SubElement(repetition, _tag("StopAtDurationEnd")).text = "false"
    ET.SubElement(trigger, _tag("StartBoundary")).text = (
        datetime.now().astimezone().replace(microsecond=0).isoformat()
    )
    ET.SubElement(trigger, _tag("Enabled")).text = "true"


def _add_principal(
    root: ET.Element, *, principal_sid: str, logon_type: str, run_level: str
) -> None:
    principals = ET.SubElement(root, _tag("Principals"))
    principal = ET.SubElement(principals, _tag("Principal"), {"id": "Author"})
    ET.SubElement(principal, _tag("UserId")).text = principal_sid
    ET.SubElement(principal, _tag("LogonType")).text = logon_type
    ET.SubElement(principal, _tag("RunLevel")).text = run_level


def _add_settings(
    root: ET.Element,
    *,
    execution_limit: str = "PT0S",
    restart_on_failure: bool = True,
) -> None:
    settings = ET.SubElement(root, _tag("Settings"))
    _setting(settings, "MultipleInstancesPolicy", "IgnoreNew")
    _setting(settings, "DisallowStartIfOnBatteries", "false")
    _setting(settings, "StopIfGoingOnBatteries", "false")
    _setting(settings, "AllowHardTerminate", "true")
    _setting(settings, "StartWhenAvailable", "true")
    _setting(settings, "RunOnlyIfNetworkAvailable", "false")
    idle = ET.SubElement(settings, _tag("IdleSettings"))
    _setting(idle, "StopOnIdleEnd", "false")
    _setting(idle, "RestartOnIdle", "false")
    _setting(settings, "AllowStartOnDemand", "true")
    _setting(settings, "Enabled", "true")
    _setting(settings, "Hidden", "true")
    _setting(settings, "RunOnlyIfIdle", "false")
    _setting(settings, "WakeToRun", "false")
    _setting(settings, "ExecutionTimeLimit", execution_limit)
    _setting(settings, "Priority", "7")
    if restart_on_failure:
        restart = ET.SubElement(settings, _tag("RestartOnFailure"))
        _setting(restart, "Interval", "PT1M")
        _setting(restart, "Count", "10")


def _add_action(
    root: ET.Element,
    paths: TaskPaths,
    *,
    module: str = "xianyu_agent.services.service_runner",
) -> None:
    actions = ET.SubElement(root, _tag("Actions"), {"Context": "Author"})
    execute = ET.SubElement(actions, _tag("Exec"))
    ET.SubElement(execute, _tag("Command")).text = str(paths.pythonw_executable)
    ET.SubElement(execute, _tag("Arguments")).text = f"-m {module}"
    ET.SubElement(execute, _tag("WorkingDirectory")).text = str(paths.project_root)


def install_task(*, startup: str = "user", project_root: Path | None = None) -> TaskPaths:
    _require_windows()
    paths = resolve_task_paths(project_root=project_root)
    sid = current_user_sid() if startup == "user" else None
    xml = build_task_xml(paths, startup=startup, user_sid=sid)
    watchdog_xml = build_watchdog_task_xml(paths, startup=startup, user_sid=sid)
    paths.xml_path.parent.mkdir(parents=True, exist_ok=True)
    _write_task_xml(paths.xml_path, xml)
    _write_task_xml(paths.watchdog_xml_path, watchdog_xml)
    _create_task(TASK_NAME, paths.xml_path)
    try:
        _create_task(WATCHDOG_TASK_NAME, paths.watchdog_xml_path)
    except WindowsServiceError:
        _delete_task(TASK_NAME, ignore_missing=True)
        raise
    return paths


def start_task() -> None:
    _require_windows()
    _run(["schtasks.exe", "/Run", "/TN", TASK_NAME])


def start_watchdog_task() -> None:
    _require_windows()
    _run(["schtasks.exe", "/Run", "/TN", WATCHDOG_TASK_NAME])


def end_task() -> None:
    _require_windows()
    _run(["schtasks.exe", "/End", "/TN", TASK_NAME])


def end_watchdog_task() -> None:
    _require_windows()
    _run(["schtasks.exe", "/End", "/TN", WATCHDOG_TASK_NAME])


def uninstall_task(*, project_root: Path | None = None) -> None:
    _require_windows()
    _delete_task(WATCHDOG_TASK_NAME, ignore_missing=True)
    _delete_task(TASK_NAME, ignore_missing=True)
    paths = resolve_task_paths(project_root=project_root)
    paths.xml_path.unlink(missing_ok=True)
    paths.watchdog_xml_path.unlink(missing_ok=True)


def query_task_status(task_name: str = TASK_NAME) -> ScheduledTaskStatus:
    _require_windows()
    exists = subprocess.run(
        ["schtasks.exe", "/Query", "/TN", task_name],
        capture_output=True,
        text=True,
        encoding=locale.getpreferredencoding(False),
        errors="replace",
        check=False,
    )
    if exists.returncode != 0:
        return ScheduledTaskStatus(installed=False)
    escaped_name = task_name.replace("'", "''")
    script = (
        f"$task=Get-ScheduledTask -TaskName '{escaped_name}' -ErrorAction Stop;"
        f"$info=Get-ScheduledTaskInfo -TaskName '{escaped_name}' -ErrorAction Stop;"
        "$last=$null;if($null -ne $info.LastRunTime){$last=$info.LastRunTime.ToString('o')};"
        "$next=$null;if($null -ne $info.NextRunTime){$next=$info.NextRunTime.ToString('o')};"
        "[pscustomobject]@{state=[string]$task.State;"
        "last_run_time=$last;"
        "last_task_result=[int64]$info.LastTaskResult;"
        "next_run_time=$next}|ConvertTo-Json -Compress"
    )
    result = _run(
        ["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", script]
    )
    try:
        data = json.loads(result.stdout.strip())
    except json.JSONDecodeError as exc:
        msg = "无法解析 Windows 任务计划状态"
        raise WindowsServiceError(msg) from exc
    return ScheduledTaskStatus(
        installed=True,
        state=str(data.get("state") or "unknown"),
        last_run_time=_optional_time(data.get("last_run_time")),
        last_task_result=int(data.get("last_task_result") or 0),
        next_run_time=_optional_time(data.get("next_run_time")),
    )


def is_service_paused(*, project_root: Path | None = None) -> bool:
    return _service_pause_path(project_root=project_root).exists()


def set_service_paused(paused: bool, *, project_root: Path | None = None) -> Path:
    path = _service_pause_path(project_root=project_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    if paused:
        path.write_text("paused\n", encoding="utf-8")
    else:
        path.unlink(missing_ok=True)
    return path


def _service_pause_path(*, project_root: Path | None) -> Path:
    if project_root is not None:
        return project_root.resolve() / "data" / "runtime" / "service.paused"
    return get_settings().service_pause_path


def _write_task_xml(path: Path, xml: str) -> None:
    path.write_text(
        f'<?xml version="1.0" encoding="UTF-16"?>\n{xml}',
        encoding="utf-16",
    )


def _create_task(task_name: str, xml_path: Path) -> None:
    _run(
        [
            "schtasks.exe",
            "/Create",
            "/TN",
            task_name,
            "/XML",
            str(xml_path),
            "/F",
        ]
    )


def _delete_task(task_name: str, *, ignore_missing: bool) -> None:
    try:
        _run(["schtasks.exe", "/Delete", "/TN", task_name, "/F"])
    except WindowsServiceError as exc:
        detail = str(exc).casefold()
        missing = any(
            marker in detail
            for marker in ("cannot find", "does not exist", "找不到", "不存在", "0x80070002")
        )
        if not (ignore_missing and missing):
            raise


def _optional_time(value: object) -> str | None:
    text = str(value or "")
    return None if not text or text.startswith("0001-01-01") else text


def _tag(name: str) -> str:
    return f"{{{TASK_NAMESPACE}}}{name}"


def _setting(parent: ET.Element, name: str, value: str) -> None:
    ET.SubElement(parent, _tag(name)).text = value


def _require_windows() -> None:
    if os.name != "nt":
        msg = "service 命令仅支持 Windows"
        raise WindowsServiceError(msg)


def _run(args: list[str]) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        args,
        capture_output=True,
        text=True,
        encoding=locale.getpreferredencoding(False),
        errors="replace",
        check=False,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        msg = f"Windows 任务计划命令失败({result.returncode}):{detail}"
        raise WindowsServiceError(msg)
    return result
