"""Normalized event schema for xianyu-agent.

All upstream WebSocket frames are parsed into one of these Pydantic models
before being passed downstream to domain/services. Downstream code never
sees raw mtop payloads, so the protocol boundary is enforceable.

Conventions:
  - Timestamps are stored as `datetime` in UTC; conversion to Asia/Shanghai
    happens at display time.
  - String IDs (`message_id`, `order_id`, `chat_id`) are optional because
    Xianyu sometimes pushes partial events.
  - `raw` keeps the original payload (truncated) for debugging only.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

# ============================================================================
#  Enums
# ============================================================================


class MessageDirection(StrEnum):
    INBOUND = "inbound"  # buyer -> seller
    OUTBOUND = "outbound"  # seller -> buyer


class MessageContentType(StrEnum):
    TEXT = "text"
    IMAGE = "image"
    CARD = "card"
    PRODUCT = "product"
    SYSTEM = "system"


class ConnectionState(StrEnum):
    IDLE = "idle"
    CONNECTING = "connecting"
    CONNECTED = "connected"
    RECONNECTING = "reconnecting"
    DISCONNECTED = "disconnected"
    ERROR = "error"


# ============================================================================
#  Raw frame (what the WS client receives from the network)
# ============================================================================


class WsFrame(BaseModel):
    """A raw WebSocket frame from the Xianyu push channel.

    `body` may be either:
      - a JSON string (parsed lazily into dict)
      - base64-encoded JSON (decoded lazily into dict)
      - raw text (passed through as `text_content`)

    Downstream parsers decide how to interpret it.
    """

    model_config = ConfigDict(extra="allow")

    code: int = 0
    packet_id: str | None = Field(default=None, alias="packetId")
    headers: dict[str, Any] = Field(default_factory=dict)
    body: str | dict[str, Any] | None = None
    received_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


# ============================================================================
#  Domain events (normalized)
# ============================================================================


class EventEnvelope(BaseModel):
    """Common metadata attached to every event."""

    model_config = ConfigDict(extra="forbid")

    event_id: str  # ULID/UUID; generated by EventBus
    account_id: str  # upstream unb
    received_at: datetime
    raw: dict[str, Any] | None = None  # truncated upstream payload, for debug


class MessageReceived(EventEnvelope):
    """A buyer sent us a message in some chat."""

    chat_id: str
    message_id: str | None = None
    item_id: str | None = None
    sent_at: datetime | None = None
    sender_id: str
    sender_name: str | None = None
    direction: Literal[MessageDirection.INBOUND] = MessageDirection.INBOUND
    content_type: MessageContentType = MessageContentType.TEXT
    content: str
    image_url: str | None = None


class MessageSent(EventEnvelope):
    """We sent a message (confirmation from the server)."""

    chat_id: str
    message_id: str | None = None
    item_id: str | None = None
    sent_at: datetime | None = None
    receiver_id: str
    direction: Literal[MessageDirection.OUTBOUND] = MessageDirection.OUTBOUND
    content_type: MessageContentType = MessageContentType.TEXT
    content: str


class OrderCreated(EventEnvelope):
    """Buyer created an order (not yet paid)."""

    order_id: str
    item_id: str | None = None
    item_title: str | None = None
    buyer_id: str
    buyer_name: str | None = None
    amount: float = 0.0


class OrderPaid(EventEnvelope):
    """Buyer paid; trigger auto-delivery."""

    order_id: str
    item_id: str | None = None
    item_title: str | None = None
    buyer_id: str
    buyer_name: str | None = None
    amount: float = 0.0
    paid_at: datetime | None = None


class OrderDelivered(EventEnvelope):
    """Order marked as delivered (by seller or system)."""

    order_id: str
    delivered_at: datetime | None = None


class SystemNotice(EventEnvelope):
    """A non-chat system event (e.g. risk control, official announcement)."""

    notice_type: str
    content: str


class ConnectionStateChanged(BaseModel):
    """Not a normal envelope: emitted by the client itself, not parsed from upstream."""

    model_config = ConfigDict(extra="forbid")

    event_id: str
    account_id: str
    state: ConnectionState
    detail: str | None = None
    occurred_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class ErrorOccurred(BaseModel):
    """Not a normal envelope: emitted when the client or parser fails."""

    model_config = ConfigDict(extra="forbid")

    event_id: str
    account_id: str
    code: str
    message: str
    occurred_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
