"""Backward-compatible imports for the split ORM model package.

Canonical model definitions now live under
``xianyu_agent.infrastructure.database.models``. Existing callers may continue
importing from ``xianyu_agent.db.models`` during the staged Phase 0 migration.
"""

from xianyu_agent.infrastructure.database.models import (
    Account,
    AccountStatus,
    AuditActor,
    AuditLog,
    Base,
    Card,
    CardConsumption,
    CardType,
    ConsumptionStatus,
    Conversation,
    Cookie,
    DaemonInstance,
    Item,
    Message,
    MessageContentType,
    MessageDirection,
    Order,
    OrderStatus,
    ReplyLog,
    ReplyRule,
    RuleType,
    TaskLog,
    TaskStatus,
    TransactionalOutbox,
    WorkerCommand,
    WorkerCommandStatus,
    WorkerDesiredState,
    WorkerStatus,
    WorkerStatusValue,
    WsCredential,
)

__all__ = [
    "Account",
    "AccountStatus",
    "AuditActor",
    "AuditLog",
    "Base",
    "Card",
    "CardConsumption",
    "CardType",
    "ConsumptionStatus",
    "Conversation",
    "Cookie",
    "DaemonInstance",
    "Item",
    "Message",
    "MessageContentType",
    "MessageDirection",
    "Order",
    "OrderStatus",
    "ReplyLog",
    "ReplyRule",
    "RuleType",
    "TaskLog",
    "TaskStatus",
    "TransactionalOutbox",
    "WorkerCommand",
    "WorkerCommandStatus",
    "WorkerDesiredState",
    "WorkerStatus",
    "WorkerStatusValue",
    "WsCredential",
]
